### ISSUE TITLE
[Bug] AttributeError: 'str' object has no attribute 'get_content'

### ISSUE THREAD

**Issue by ericwb** [phidatahq/phidata#5898]
### Description

The example listed on this page
https://docs.agno.com/basics/hooks/overview#basic-example
raises an AttributeError.

This did work for Agno version 2.3.5, but after we updated to 2.3.21, our validate_input_length function is failing with an exception.

### Steps to Reproduce

1. Follow instructions at https://docs.agno.com/basics/hooks/overview#basic-example to create a pre-hook
2. We changed the code slightly to use `input_tokens = tokens.count_tokens(run_input.input_content_string())` to count tokens
3. Full code is below:

```
class CIAgent(Agent):
    def __init__(self, name, agent_config, retry_attempts=DEFAULT_RETRY_ATTEMPTS):
        super().__init__()
        self.name = name
        self.retries = retry_attempts
        self.config = agent_config
        self.markdown = True
        self.description = self.config["role"]
        self.instructions = self.config["instructions"]
        self.model = utils.load_model(self.config.get("model"))
        self.scope = self.config.get("scope", "file")
        self.add_context = True
        self.output_schema = InlineReviewOutput if self.scope == "file" else GlobalReviewOutput
        self.use_json_mode = True
        self.telemetry = False
        self.pre_hooks=[self.validate_input_length]

    def validate_input_length(self, run_input: RunInput) -> None:
        """Pre-hook to validate input length."""
        input_tokens = tokens.count_tokens(run_input.input_content_string())
        logger.info(
            f"Using {input_tokens} input tokens of {self.model.input_token_limit}"
            " available."
        )

        if input_tokens > self.model.input_token_limit:
            raise InputCheckError(
                f"Input too large. Max of {self.model.input_token_limit} tokens allowed",
                check_trigger=CheckTrigger.INPUT_NOT_ALLOWED,
            )
```

### Expected Behavior

Shouldn't raise an exception. In fact it didn't in Agno 2.3.5. Occurs after upgrading to 2.3.21.

### Actual Behavior

```
ERROR    Pre-hook #1 execution failed: 'str' object has no attribute 'get_content'                                                    
ERROR    'str' object has no attribute 'get_content'                                                                                  
         Traceback (most recent call last):                                                                                           
           File "/Users/eb900390/.pyenv/versions/3.11.14/lib/python3.11/site-packages/agno/agent/agent.py", line 4751, in             
         _aexecute_pre_hooks                                                                                                          
             hook(**filtered_args)                                                                                                    
           File "/Users/eb900390/workspace/ai-review-bot/ai_review_bot/libs/agent.py", line 214, in validate_input_length             
             input_tokens = tokens.count_tokens(run_input.input_content)                                                              
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                              
           File "/Users/eb900390/.pyenv/versions/3.11.14/lib/python3.11/site-packages/agno/utils/tokens.py", line 647, in count_tokens
             total += _count_message_tokens(msg, model_id)                                                                            
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                            
           File "/Users/eb900390/.pyenv/versions/3.11.14/lib/python3.11/site-packages/agno/utils/tokens.py", line 578, in             
         _count_message_tokens                                                                                                        
             content = message.get_content(use_compressed_content=True)                                                               
                       ^^^^^^^^^^^^^^^^^^^                                                                                            
         AttributeError: 'str' object has no attribute 'get_content'   
```

### Screenshots or Logs (if applicable)

```
ERROR    Pre-hook #1 execution failed: 'str' object has no attribute 'get_content'                                                    
ERROR    'str' object has no attribute 'get_content'                                                                                  
         Traceback (most recent call last):                                                                                           
           File "/Users/eb900390/.pyenv/versions/3.11.14/lib/python3.11/site-packages/agno/agent/agent.py", line 4751, in             
         _aexecute_pre_hooks                                                                                                          
             hook(**filtered_args)                                                                                                    
           File "/Users/eb900390/workspace/ai-review-bot/ai_review_bot/libs/agent.py", line 214, in validate_input_length             
             input_tokens = tokens.count_tokens(run_input.input_content)                                                              
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                              
           File "/Users/eb900390/.pyenv/versions/3.11.14/lib/python3.11/site-packages/agno/utils/tokens.py", line 647, in count_tokens
             total += _count_message_tokens(msg, model_id)                                                                            
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                            
           File "/Users/eb900390/.pyenv/versions/3.11.14/lib/python3.11/site-packages/agno/utils/tokens.py", line 578, in             
         _count_message_tokens                                                                                                        
             content = message.get_content(use_compressed_content=True)                                                               
                       ^^^^^^^^^^^^^^^^^^^                                                                                            
         AttributeError: 'str' object has no attribute 'get_content'   
```

### Environment

```markdown
- OS: macOS
- Agno: 2.3.21
- Python: 3.11.14
```

**Comment by ericwb** [comment]
I was able to workaround the problem by using `tokens.count_text_tokens()`.

However, from looking at the code, it seems the new version of `tokens.count_tokens()` is not backwards compatible.

**Comment by dirkbrnd** [comment]
@ericwb Sorry about that, `tokens.count_tokens()` is part of our compression logic that is in beta and subject to change, but I can see how this was unexpected. 

We should have a better util here, I agree. But yes `tokens.count_text_tokens()` is the correct one to use.

I'll close this issue for now then
