### ISSUE TITLE
[Bug] Inherited mypy/style-check error from main branch (agno/team/team.py line 4275) breaks PR validation

### ISSUE THREAD

**Issue by KarthikeyaKollu** [phidatahq/phidata#4789]
### Description

Description:
After merging the latest main branch into my working branch, all new PRs are failing the style-check due to a mypy error:

`agno/team/team.py:4275: error: Item "None" of "Optional[list[Union[Toolkit, Callable[..., Any], Function, dict[Any, Any]]]]" has no attribute "__iter__" (not iterable) [union-attr] Found 1 error in 1 file (checked 524 source files) Process completed with exit code 1 `
This type error was not present before merging main. It now affects anyone attempting to validate a PR after updating from main, even if their code did not touch this file.

My affected PRs:

#4757 ([refactor] Refactor PDF readers for efficiency and code reuse)

#4717 ([fix] preserve extra_content on early return in _clean_page_numbers)

#4722 ([feat] Add ImageReader feature with OCR and Vision modes)

Resolving this will unblock PR validation for all contributors.

### Steps to Reproduce

1. Fork and clone agno-agi/agno repository
2. Create a feature/refactor branch (e.g., 'refactor/pdf-reader')
3. Merge latest main branch into your working branch
4. Push your branch and run CI/validation
5. Observe style-check/mypy failure from agno/team/team.py line 4275

### Expected Behavior

PRs without code changes in agno/team/team.py should pass the mypy type check and style validation successfully.

### Actual Behavior

Style-check fails for all contributors who inherit the latest main branch, blocking PR validation even when their code changes don't touch the problematic file.

### Screenshots or Logs (if applicable)

Error log from GitHub Actions style-check:

```
agno/team/team.py:4275: error: Item "None" of "Optional[list[Union[Toolkit, Callable[..., Any], Function, dict[Any, Any]]]]" has no attribute "__iter__" (not iterable) [union-attr]
Found 1 error in 1 file (checked 524 source files)
Process completed with exit code 1
```

This error appears consistently across multiple PRs after merging main branch, including:
- PR #4757 (Refactor PDF readers)
- PR #4717 (preserve extra_content fix)
- PR #4722 (Add ImageReader feature)

### Environment

```markdown
- Python version: Latest
- agno version: Latest main branch
- Operating System: Any
- CI/CD: GitHub Actions style-check workflow
```

### Possible Solutions (optional)

Add a guard for None when iterating in agno/team/team.py line 4275. The error suggests that an Optional list is being iterated without checking if it's None first. Consider adding:

```python
if some_list is not None:
    for item in some_list:
        # existing iteration logic
```

**Comment by ysolanky** [comment]
This has been fixed! Thank you for the shout

**Comment by KarthikeyaKollu** [comment]
@ysolanky  Thanks!

can you look in to these PR's

https://github.com/agno-agi/agno/pull/4757 ([refactor] Refactor PDF readers for efficiency and code reuse)

https://github.com/agno-agi/agno/pull/4717 ([fix] preserve extra_content on early return in _clean_page_numbers)

https://github.com/agno-agi/agno/pull/4722 ([feat] Add ImageReader feature with OCR and Vision modes)
