### PR TITLE
cookbook: v2.5 merge fixes + comprehensive testing

### PR DESCRIPTION
**Pull request by Mustafa-Esoofally**
## Summary

Merges Ashpreet's `cookbook-improvements` branch (#6536) with v2.5 pre-release fixes from `cookbooks/v2.5-testing`. Includes comprehensive post-merge validation of all core cookbook directories.

**What changed:**
- Restructured `02_agents/` into 16 numbered subdirectories (01_quickstart through 16_skills)
- Applied v2.5 testing audit fixes across all cookbook directories
- Fresh TEST_LOG.md results for 440 cookbook files across 4 core directories

**Test results (2026-02-12):**

| Directory | Total | PASS | FAIL | SKIP |
|-----------|-------|------|------|------|
| 02_agents | 104 | 88 | 8 | 8 |
| 03_teams | 121 | 100 | 16 | 5 |
| 04_workflows | 78 | 60 | 8 | 10 |
| 07_knowledge | 137 | 63 | 8 | 66 |
| **Totals** | **440** | **311** | **40** | **89** |

All 40 failures are pre-existing (timeouts, missing test assets, external API changes). Zero regressions from the merge.

## Type of change

- [x] Improvement
- [x] Other: Cookbook restructuring + testing

---

## Checklist

- [x] Code complies with style guidelines
- [x] Ran format/validation scripts (`./scripts/format.sh` and `./scripts/validate.sh`)
- [x] Self-review completed
- [x] Examples and guides: Relevant cookbook examples have been included or updated (if applicable)
- [x] Tested in clean environment

---

## Additional Notes

- 415 files changed, 10108 insertions, 4634 deletions
- PgVector required for knowledge/session/RAG cookbooks (tested with local Docker)
- SKIPs are expected: cloud services, external vector DBs, HITL interactive examples
- Builds on #6536 (cookbook-improvements)

### CODE REVIEW

File: cookbook/91_tools/airflow_tools.py [hunk 1]
```diff
@@ -33,8 +33,8 @@
     tools=[
         AirflowTools(
             dags_dir="tmp/dags",
-            enable_save_dag=False,  # Disable DAG creation
-            enable_read_dag=True,  # Enable DAG reading
+            enable_save_dag_file=False,  # Disable DAG creation
```
Comment (Mustafa-Esoofally) [inline cookbook/91_tools/airflow_tools.py:36]: **Crash fix (TypeError):** `enable_save_dag` and `enable_read_dag` were renamed to `enable_save_dag_file` and `enable_read_dag_file` in `AirflowTools.__init__()`. The old names flow through `**kwargs` to `Toolkit.__init__()` which doesn't accept them, causing:
```
TypeError: Toolkit.__init__() got an unexpected keyword argument 'enable_save_dag'
```
Verified: crashes on import.

File: cookbook/91_tools/wikipedia_tools.py [hunk 2]
```diff
@@ -15,29 +15,11 @@
...
-            enable_search_wikipedia_and_update_knowledge_base=False,
-        )
-    ]
-)
-
-# Example 2: Enable all Wikipedia functions
-agent_all = Agent(tools=[WikipediaTools(all=True)])
-
-# Example 3: Wikipedia with knowledge base integration
+agent = Agent(tools=[WikipediaTools()])
```
Comment (Mustafa-Esoofally) [inline cookbook/91_tools/wikipedia_tools.py:18]: **Crash fix (TypeError):** `WikipediaTools` was refactored to remove per-feature flags (`enable_search_wikipedia`, `enable_search_wikipedia_and_update_knowledge_base`). It now only accepts `knowledge` and `all`. Old flags pass through `**kwargs` to `Toolkit.__init__()` which rejects them:
```
TypeError: Toolkit.__init__() got an unexpected keyword argument 'enable_search_wikipedia'
```
Verified: crashes on import.

File: cookbook/91_tools/moviepy_video_tools.py [hunk 3]
```diff
@@ -16,7 +16,7 @@
 
 
 video_tools = MoviePyVideoTools(
-    process_video=True, generate_captions=True, embed_captions=True
+    enable_process_video=True, enable_generate_captions=True, enable_embed_captions=True
```
Comment (Mustafa-Esoofally) [inline cookbook/91_tools/moviepy_video_tools.py:19]: **Crash fix (TypeError):** `MoviePyVideoTools` renamed params from `process_video`/`generate_captions`/`embed_captions` to `enable_process_video`/`enable_generate_captions`/`enable_embed_captions`. Old names flow through `**kwargs` to `Toolkit.__init__()` and crash:
```
TypeError: Toolkit.__init__() got an unexpected keyword argument 'process_video'
```
Same fix applied in `cookbook/02_agents/12_multimodal/video_caption.py` and `cookbook/03_teams/multimodal/video_caption_generation.py`.

File: cookbook/05_agent_os/advanced_demo/_teams.py [hunk 4]
```diff
@@ -33,9 +33,7 @@
     role="Handle financial data requests",
     model=Claude(id="claude-3-7-sonnet-latest"),
     db=PostgresDb(db_url=db_url, session_table="finance_agent_sessions"),
-    tools=[
-        YFinanceTools(stock_price=True, analyst_recommendations=True, company_info=True)
-    ],
+    tools=[YFinanceTools()],
```
Comment (Mustafa-Esoofally) [inline cookbook/05_agent_os/advanced_demo/_teams.py:36]: **Crash fix (TypeError):** `YFinanceTools` was refactored to remove per-feature flags (`stock_price`, `analyst_recommendations`, `company_info`, etc.). It now registers all methods by default. Old flags pass through `**kwargs` to `Toolkit.__init__()` and crash:
```
TypeError: Toolkit.__init__() got an unexpected keyword argument 'stock_price'
```
Same pattern fixed in `cookbook/05_agent_os/interfaces/whatsapp/reasoning_agent.py`.

File: cookbook/90_models/langdb/data_analyst.py [hunk 5]
```diff
@@ -10,9 +10,7 @@
 # Create Agent
 # ---------------------------------------------------------------------------
 
-duckdb_tools = DuckDbTools(
-    create_tables=False, export_tables=False, summarize_tables=False
-)
+duckdb_tools = DuckDbTools()
```
Comment (Mustafa-Esoofally) [inline cookbook/90_models/langdb/data_analyst.py:13]: **Crash fix (TypeError):** `DuckDbTools` was refactored to remove per-feature flags (`create_tables`, `export_tables`, `summarize_tables`). Old flags pass through `**kwargs` to `Toolkit.__init__()` and crash:
```
TypeError: Toolkit.__init__() got an unexpected keyword argument 'create_tables'
```

File: cookbook/03_teams/reasoning/reasoning_multi_purpose_team.py [hunk 6]
```diff
@@ -118,15 +118,7 @@
...
-    tools=[
-        GithubTools(
-            list_issues=True,
-            list_issue_comments=True,
-            get_pull_request=True,
-            get_issue=True,
-            get_pull_request_comments=True,
-        )
-    ],
+    tools=[GithubTools()],
```
Comment (Mustafa-Esoofally) [inline cookbook/03_teams/reasoning/reasoning_multi_purpose_team.py:121]: **Crash fix (TypeError):** `GithubTools` was refactored to remove per-feature flags (`list_issues`, `get_pull_request`, etc.). It now registers all methods by default. Old flags pass through `**kwargs` to `Toolkit.__init__()` and crash. Same pattern on line 131 for `PythonTools` (removed `list_files`, `run_files`, `uv_pip_install`).

File: cookbook/91_tools/aws_lambda_tools.py [hunk 7]
```diff
@@ -40,8 +40,6 @@
             region_name="us-east-1",
             enable_list_functions=True,
             enable_invoke_function=True,
```
Comment (Mustafa-Esoofally) [inline cookbook/91_tools/aws_lambda_tools.py:42]: **Crash fix (TypeError):** `AWSLambdaTools` only has `enable_list_functions` and `enable_invoke_function`. The old flags `enable_create_function`, `enable_update_function`, `enable_delete_function` were removed. They pass through `**kwargs` to `Toolkit.__init__()` and crash:
```
TypeError: Toolkit.__init__() got an unexpected keyword argument 'enable_create_function'
```

File: cookbook/91_tools/crawl4ai_tools.py [hunk 8]
```diff
@@ -39,54 +38,27 @@
     tools=[
         Crawl4aiTools(
             use_pruning=True,
-            enable_crawl_page=True,
-            enable_extract_content=True,
-            enable_extract_links=False,  # Disable link extraction
-            enable_take_screenshot=False,  # Disable screenshot functionality
+            enable_crawl=True,
```
Comment (Mustafa-Esoofally) [inline cookbook/91_tools/crawl4ai_tools.py:41]: **Crash fix (TypeError):** `Crawl4aiTools` was simplified to a single `enable_crawl` flag. Old flags (`enable_crawl_page`, `enable_extract_content`, `enable_extract_links`, `enable_take_screenshot`) no longer exist and crash via `**kwargs` passthrough to `Toolkit.__init__()`.

File: cookbook/03_teams/01_quickstart/05_team_history.py [hunk 9]
```diff
@@ -42,7 +42,6 @@
     db=SqliteDb(
         db_file="tmp/multi_lingual_q_and_a_team.db"
     ),  # Add a database to store the conversation history. This is a requirement for history to work correctly.
-    pass_user_input_to_members=True,  # Send input directly to members (replaces determine_input_for_members=False).
     respond_directly=True,
```
Comment (Mustafa-Esoofally) [inline cookbook/03_teams/01_quickstart/05_team_history.py:45]: **Crash fix (TypeError):** `pass_user_input_to_members` does not exist on `Team`. Since `Team` is a Pydantic model, passing unknown fields raises:
```
TypeError: Team.__init__() got an unexpected keyword argument 'pass_user_input_to_members'
```
Same fix in `cookbook/03_teams/structured_input_output/pydantic_input.py` and `cookbook/05_agent_os/advanced_demo/teams_demo.py`.

File: cookbook/08_learning/09_decision_logs/01_basic_decision_log.py [hunk 10]
```diff
@@ -65,6 +65,6 @@
 
     # View logged decisions
     print("\n=== Decisions Logged ===\n")
-    decision_store = agent.get_learning_machine().decision_log_store
+    decision_store = agent.learning_machine.decision_log_store
```
Comment (Mustafa-Esoofally) [inline cookbook/08_learning/09_decision_logs/01_basic_decision_log.py:68]: **Crash fix (AttributeError):** `agent.get_learning_machine()` does not exist. `learning_machine` is a `@property` on Agent (not a method), so the correct access is `agent.learning_machine`.
```
AttributeError: 'Agent' object has no attribute 'get_learning_machine'
```
Same fix in `02_decision_log_always.py`.

File: cookbook/04_workflows/06_advanced_concepts/session_state/rename_session.py [hunk 11]
```diff
@@ -65,4 +67,4 @@
     )
 
     article_workflow.set_session_name(autogenerate=True)
-    print(f"New session name: {article_workflow.session_name}")
+    print(f"New session name: {article_workflow.get_session_name()}")
```
Comment (Mustafa-Esoofally) [inline cookbook/04_workflows/06_advanced_concepts/session_state/rename_session.py:70]: **Crash fix (AttributeError):** `workflow.session_name` does not exist as a property. The correct API is `workflow.get_session_name()` (a method).
```
AttributeError: 'Workflow' object has no attribute 'session_name'
```

File: cookbook/04_workflows/06_advanced_concepts/session_state/rename_session.py [hunk 12]
```diff
@@ -56,6 +57,7 @@
     article_workflow = Workflow(
         description="Automated article creation from research to writing",
         steps=[article_creation_sequence],
+        db=SqliteDb(db_file="tmp/workflows.db"),
```
Comment (Mustafa-Esoofally) [inline cookbook/04_workflows/06_advanced_concepts/session_state/rename_session.py:60]: **Crash fix (missing db):** `set_session_name()` persists the session name to the database. Without `db=`, the workflow has no storage backend and `set_session_name(autogenerate=True)` would fail with `TypeError: NoneType has no len()`.

File: cookbook/06_storage/postgres/async_postgres/async_postgres_for_agent.py [hunk 13]
```diff
@@ -24,9 +24,14 @@
     add_datetime_to_context=True,
 )
 
+
 # ---------------------------------------------------------------------------
 # Run Agent
 # ---------------------------------------------------------------------------
```
Comment (Mustafa-Esoofally) [inline cookbook/06_storage/postgres/async_postgres/async_postgres_for_agent.py:30]: **Best practice fix (asyncio anti-pattern):** Old code called `asyncio.run()` twice at module level with the same agent. While this works in Python 3.12+, it's an anti-pattern — the first call closes the event loop and its associated async resources (httpx clients, DB connections). Wrapping in a single `async def main()` is the correct pattern.

Same fix in `cookbook/06_storage/sqlite/async_sqlite/async_sqlite_for_agent.py` and `cookbook/11_memory/08_memory_tools.py`.

File: cookbook/03_teams/search_coordination/01_coordinated_agentic_rag.py [hunk 14]
```diff
@@ -26,7 +26,7 @@
     ),
 )
 
-knowledge.insert_many(urls=["https://docs.agno.com/basics/agents/overview.md"])
+knowledge.insert_many(urls=["https://docs.agno.com/agents/overview.md"])
```
Comment (Mustafa-Esoofally) [inline cookbook/03_teams/search_coordination/01_coordinated_agentic_rag.py:29]: **Silent failure fix (404 URL):** The docs site restructured URLs — `docs.agno.com/basics/agents/overview.md` was moved to `docs.agno.com/agents/overview.md`. The old URL returns 404, causing `knowledge.insert_many()` to silently insert no documents (the agent has an empty knowledge base and can't answer questions).

Same URL fix applied across 9 files in `search_coordination/`, `07_knowledge/`, and `92_integrations/`.

File: cookbook/03_teams/metrics/01_team_metrics.py [hunk 15]
```diff
@@ -20,15 +19,6 @@
 db_url = "postgresql+psycopg://ai:ai@localhost:5532/ai"
 db = PostgresDb(db_url=db_url, session_table="team_metrics_sessions")
```
Comment (Mustafa-Esoofally) [inline cookbook/03_teams/metrics/01_team_metrics.py:20]: **Logic bug fix (variable overwrite):** The old code defined `db = PostgresDb(...)` on this line, then immediately overwrote it with `db = SurrealDb(...)` 8 lines below. Since SurrealDB isn't available locally, the team would crash at runtime. Removed the dead SurrealDB block so the intended PostgresDb is used.

File: cookbook/02_agents/07_knowledge/agentic_rag_with_reasoning.py [hunk 16]
```diff
@@ -33,7 +33,7 @@
 # Create Agent
 # ---------------------------------------------------------------------------
 agent = Agent(
-    model=OpenAIResponses(id="gpt-5.2"),
+    model=Claude(id="claude-sonnet-4-20250514"),
     # Agentic RAG is enabled by default when `knowledge` is provided to the Agent.
```
Comment (Mustafa-Esoofally) [inline cookbook/02_agents/07_knowledge/agentic_rag_with_reasoning.py:37]: **Model update:** Changed from `OpenAIResponses(id="gpt-5.2")` to `Claude(id="claude-sonnet-4-20250514")`. The `OpenAIResponses` class requires an API key and model ID that may not be available. Using Claude with Cohere embedder/reranker is a more portable demo.

**Comment by Mustafa-Esoofally** [comment]
Superseded by #6546 (squashed with #6539 into a single clean PR)
